project_id = "ufjvcpshkmrdqayjrwkh"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.delete-user]
    verify_jwt = true
  [functions.invite-user]
    verify_jwt = true
  [functions.notify-installers]
    verify_jwt = true
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-transactional-email]
    verify_jwt = false
  [functions.handle-email-unsubscribe]
    verify_jwt = false
